// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(ShowsCenterContext))]
    [Migration("20260614234006_UpdatePasswordLengthInDbContext")]
    partial class UpdatePasswordLengthInDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC078D1DB473");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Order_date");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC077013FBAE");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Entities.OrderedSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Col")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("Order_id");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("Section_id");

                    b.Property<int>("ShowId")
                        .HasColumnType("int")
                        .HasColumnName("Show_id");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__OrderedS__3214EC070B4BBFF8");

                    b.HasIndex("OrderId");

                    b.HasIndex("SectionId");

                    b.HasIndex("ShowId");

                    b.ToTable("OrderedSeats");
                });

            modelBuilder.Entity("Entities.PasswordResetCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Code");

                    b.ToTable("PasswordResetCodes");
                });

            modelBuilder.Entity("Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .IsFixedLength();

                    b.Property<string>("ProfileImgUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nchar(2000)")
                        .HasColumnName("Profile_img_url")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__Provider__3214EC07753D54FB");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("Entities.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rating_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("host");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("method");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("path");

                    b.Property<DateTime?>("RecordDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("record_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Referer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("referer");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("user_agent");

                    b.HasKey("RatingId");

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<int>("SectionType")
                        .HasColumnType("int")
                        .HasColumnName("Section_type");

                    b.Property<int>("ShowId")
                        .HasColumnType("int")
                        .HasColumnName("Show_id");

                    b.HasKey("Id")
                        .HasName("PK__Sections__3214EC0761B18F1A");

                    b.HasIndex("ShowId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Entities.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .IsFixedLength();

                    b.Property<TimeOnly>("BeginTime")
                        .HasColumnType("time")
                        .HasColumnName("Begin_time");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("Category_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength();

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("End_time");

                    b.Property<string>("ImgUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nchar(2000)")
                        .HasColumnName("Img_url")
                        .IsFixedLength();

                    b.Property<int>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("Provider_id");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__tmp_ms_x__3214EC072BDFDAA9");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .HasColumnName("email_address")
                        .IsFixedLength();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .HasColumnName("first_name")
                        .IsFixedLength();

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .HasColumnName("last_name")
                        .IsFixedLength();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nchar(255)")
                        .HasColumnName("password")
                        .IsFixedLength();

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(13)
                        .HasColumnType("nchar(13)")
                        .HasColumnName("phone_number")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.HasOne("Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.OrderedSeat", b =>
                {
                    b.HasOne("Entities.Order", "Order")
                        .WithMany("OrderedSeats")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrdSeats_Orders");

                    b.HasOne("Entities.Section", "Section")
                        .WithMany("OrderedSeats")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK_OrdSeats_Section");

                    b.HasOne("Entities.Show", "Show")
                        .WithMany("OrderedSeats")
                        .HasForeignKey("ShowId")
                        .IsRequired()
                        .HasConstraintName("FK_OrdSeats_Shows");

                    b.Navigation("Order");

                    b.Navigation("Section");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Entities.Section", b =>
                {
                    b.HasOne("Entities.Show", "Show")
                        .WithMany("Sections")
                        .HasForeignKey("ShowId")
                        .IsRequired()
                        .HasConstraintName("FK_Sections_Shows");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Entities.Show", b =>
                {
                    b.HasOne("Entities.Category", "Category")
                        .WithMany("Shows")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Shows_Categories");

                    b.HasOne("Entities.Provider", "Provider")
                        .WithMany("Shows")
                        .HasForeignKey("ProviderId")
                        .IsRequired()
                        .HasConstraintName("FK_Shows_Providers");

                    b.Navigation("Category");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Navigation("Shows");
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.Navigation("OrderedSeats");
                });

            modelBuilder.Entity("Entities.Provider", b =>
                {
                    b.Navigation("Shows");
                });

            modelBuilder.Entity("Entities.Section", b =>
                {
                    b.Navigation("OrderedSeats");
                });

            modelBuilder.Entity("Entities.Show", b =>
                {
                    b.Navigation("OrderedSeats");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
