// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Show
{
    public int Id { get; set; }

    public string Title { get; set; }

    public DateOnly Date { get; set; }

    public TimeOnly BeginTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public string Audience { get; set; }

    public string Sector { get; set; }

    public string Description { get; set; }

    public string ImgUrl { get; set; }

    public int ProviderId { get; set; }

    public int CategoryId { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<OrderedSeat> OrderedSeats { get; set; } = new List<OrderedSeat>();

    public virtual Provider Provider { get; set; }

    public virtual ICollection<Section> Sections { get; set; } = new List<Section>();
}