// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Order
{
    public int Id { get; set; }

    public DateTime OrderDate { get; set; }

    public int UserId { get; set; }

    public double Price { get; set; }

    public virtual ICollection<OrderedSeat> OrderedSeats { get; set; } = new List<OrderedSeat>();

    public virtual User User { get; set; }
}