// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class OrderedSeat
{
    public int Id { get; set; }

    public int SectionId { get; set; }

    public int Row { get; set; }

    public int Col { get; set; }

    public int OrderId { get; set; }

    public int Status { get; set; } = 1;

    public int ShowId { get; set; }

    public virtual Order Order { get; set; }

    public virtual Section Section { get; set; }

    public virtual Show Show { get; set; }
}