// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Provider
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string ProfileImgUrl { get; set; }

    public virtual ICollection<Show> Shows { get; set; } = new List<Show>();
}