// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Section
{
    public int Id { get; set; }

    public decimal? Price { get; set; }

    public int ShowId { get; set; }

    public int SectionType { get; set; }

    public virtual ICollection<OrderedSeat> OrderedSeats { get; set; } = new List<OrderedSeat>();

    public virtual Show Show { get; set; }
}