// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Entities;
using Microsoft.Extensions.Configuration;

namespace Entities;

public partial class ShowsCenterContext : DbContext
{
    public ShowsCenterContext()
    {
    }

    public ShowsCenterContext(DbContextOptions<ShowsCenterContext> options)
        : base(options)
    {
    }
    //protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //{
    //    if (!optionsBuilder.IsConfigured)
    //    {
    //        // 🚨 ודא ששורה זו קיימת!
    //        optionsBuilder.UseSqlServer("Data Source=michal;Initial Catalog=ShowsCenter;Integrated Security=True;Pooling=False;Trust Server Certificate=True;MultipleActiveResultSets=true");
    //    }
    //}
    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderedSeat> OrderedSeats { get; set; }

    public virtual DbSet<Provider> Providers { get; set; }

    public virtual DbSet<Section> Sections { get; set; }

    public virtual DbSet<Show> Shows { get; set; }

    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<PasswordResetCode> PasswordResetCodes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Categori__3214EC078D1DB473");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .IsFixedLength();
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Orders__3214EC077013FBAE");

            entity.Property(e => e.OrderDate)
                .HasColumnType("datetime")
                .HasColumnName("Order_date");
            entity.Property(e => e.Price).HasColumnType("money");
            entity.Property(e => e.UserId).HasColumnName("User_id");

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_User");
        });

        modelBuilder.Entity<OrderedSeat>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderedS__3214EC070B4BBFF8");

            entity.Property(e => e.OrderId).HasColumnName("Order_id");
            entity.Property(e => e.SectionId).HasColumnName("Section_id");
            entity.Property(e => e.ShowId).HasColumnName("Show_id");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderedSeats)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrdSeats_Orders");

            entity.HasOne(d => d.Section).WithMany(p => p.OrderedSeats)
                .HasForeignKey(d => d.SectionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrdSeats_Section");

            entity.HasOne(d => d.Show).WithMany(p => p.OrderedSeats)
                .HasForeignKey(d => d.ShowId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrdSeats_Shows");
        });

        modelBuilder.Entity<Provider>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Provider__3214EC07753D54FB");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(30)
                .IsFixedLength();
            entity.Property(e => e.ProfileImgUrl)
                .HasMaxLength(2000)
                .IsFixedLength()
                .HasColumnName("Profile_img_url");
        });

        modelBuilder.Entity<Section>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Sections__3214EC0761B18F1A");

            entity.Property(e => e.Price).HasColumnType("money");
            entity.Property(e => e.ShowId).HasColumnName("Show_id");
            entity.Property(e => e.SectionType).HasColumnName("Section_type");

            entity.HasOne(d => d.Show).WithMany(p => p.Sections)
                .HasForeignKey(d => d.ShowId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sections_Shows");
        });

        modelBuilder.Entity<Show>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC072BDFDAA9");

            entity.Property(e => e.Audience)
                .IsRequired()
                .HasMaxLength(15)
                .IsFixedLength();
            entity.Property(e => e.BeginTime).HasColumnName("Begin_time");
            entity.Property(e => e.EndTime).HasColumnName("End_time");
            entity.Property(e => e.CategoryId).HasColumnName("Category_id");
            entity.Property(e => e.Description)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.ImgUrl)
                .HasMaxLength(2000)
                .IsFixedLength()
                .HasColumnName("Img_url");
            entity.Property(e => e.ProviderId).HasColumnName("Provider_id");
            entity.Property(e => e.Sector)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(20)
                .IsFixedLength();

            entity.HasOne(d => d.Category).WithMany(p => p.Shows)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Shows_Categories");

            entity.HasOne(d => d.Provider).WithMany(p => p.Shows)
                .HasForeignKey(d => d.ProviderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Shows_Providers");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.EmailAddress)
                .HasMaxLength(30)
                .HasColumnName("email_address");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(30)
                .IsFixedLength()
                .HasColumnName("first_name");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(30)
                .IsFixedLength()
                .HasColumnName("last_name");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password");
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(13)
                .IsFixedLength()
                .HasColumnName("phone_number");
        });

        modelBuilder.Entity<PasswordResetCode>(entity =>
        {
            entity.HasIndex(p => new { p.Email, p.Code });

        });

        modelBuilder.Entity<Rating>(entity =>
        {
            entity.HasKey(e => e.RatingId);
            entity.ToTable("ratings");
            entity.Property(e => e.RatingId)
                .HasColumnName("rating_id");
            entity.Property(e => e.Host)
                .HasMaxLength(100)
                .HasColumnName("host");
            entity.Property(e => e.Method)
                .HasMaxLength(10)
                .HasColumnName("method");
            entity.Property(e => e.Path)
                .HasMaxLength(500)
                .HasColumnName("path");
            entity.Property(e => e.RecordDate)
                .HasColumnName("record_date")
                .HasDefaultValueSql("GETDATE()");
            entity.Property(e => e.Referer)
                .HasMaxLength(500)
                .HasColumnName("referer");
            entity.Property(e => e.UserAgent)
                .HasMaxLength(1000)
                .HasColumnName("user_agent");
        });

        OnModelCreatingPartial(modelBuilder);
    }



    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
